version: "3.7"
services:
  backend:
    build: backend
    depends_on: 
    - db
  db:
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    image: mysql:5.7
    restart: always
    secrets:
    - db-password
    volumes:
    - db-data:/var/lib/mysql
  proxy:
    build: proxy
    ports:
    - 80:80
    depends_on: 
    - backend
volumes:
  db-data: {}
secrets:
  db-password:
    file: db/password.txt
